aboutPage: true

# - markdown: redcarpet
highlighter: rouge

domain_# - name: "http://[HOSTNAME]"
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_short# - name: 'your-disqus-shortname'

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

title: "Dave"
tagline: ""
description: "Follow <a href=\"https://micro.blog/fossil12\">@fossil12 on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/fossil12\">@fossil12 on Micro.blog</a>."
baseurl: ""
url: "https://fossil12.micro.blog"
markdown: "kramdown"
username: "fossil12"
microblog_user: "fossil12"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Dave"
name: "Dave"
gravatar_hash: "f3968efafd906d34d2902c627e0447eb"
avatar: "https://micro.blog/fossil12/avatar.jpg"
full_name: "Dave"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "Poland"
site_id: "1292"
gems: ["jekyll-paginate"]
itunes_description: "Applegeek. Software Engineer. Wannabe Designer. Digital Native. CS Student at ETH Zurich. Past intern at Strava, exchange at Penn. Volunteer youth work at Jubla. WWDC 2018 Scholar."
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Dave"
itunes_email: ""
podcast: false